apiVersion: v1
kind: Service
metadata:
  labels:
    name: goapi
    role: service
  name: goapiservice
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
      app: web
      type: api

  type: "LoadBalancer"