apiVersion: v1
kind: Service
metadata:
  labels:
    name: redi
    role: service
  name: redis-master
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
      app: redis
      type: master