apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: "redisslave"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        type: "slave"
    spec:
      containers:
        - name: redis
          image: "jojiisacth/redis"
          command:
            - "./run.sh"
        
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"
            - name: cluster
              containerPort: 16379
              protocol: "TCP"
         